apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-role-binding
subjects:
- kind: ServiceAccount
  name: deployment-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io
